### ISSUE TITLE
Crudmaker do not create repository

### ISSUE THREAD

**Issue by mistre83** [YABhq/CrudMaker#17]
Hi,
i have update crudmaker to the latest version and with this command:

`php artisan crudmaker:new Product --schema="id:increments" --migration`

All file are generated, but the **repository** is not (only the model).

After the update, i've noticed that `Model.txt` now is outside the Repository folder.
Searching in all project i see a reference to `Model.txt` in `CrudGenerator.php` but no reference to `Repository.txt`

I have miss something?

**Comment by casperboone** [comment]
Hi,
Since 1.1.0 CrudMaker does no longer generate repositories, see https://github.com/YABhq/CrudMaker/blob/develop/changelog.md#v110---2016-09-06. If you need it, make sure to lock to an older version.

**Comment by mistre83** [comment]
Mhhh i understand. But now when i generate a crud it create routes in `Http\routes.php` and not in `routes\web.php` folder.

More.. it not create me Repository and the service still depend to repository (that do not exists).
I have run `composer update` and `php artisan vendor:publish --provider="Yab\CrudMaker\CrudMakerProvider"`
I should run other commands to have "the updated version" ?

**Comment by mistre83** [comment]
Yes is true, i have added this in my `composer.json`:
```
"yab/crudmaker": "1.0.8",
"yab/laracogs": "2.0.0",
```

And now i have successfully downgrade the version.
