### ISSUE TITLE
Cannot get relationships to work

### ISSUE THREAD

**Issue by damian-nz** [YABhq/CrudMaker#24]
Hey there,

I am testing this out as a part of Laracogs and am really keen to use it for my next project. I have a clean install running on a Homestead Vagrant box and I cannot get the relationships option to work for me.

If I run this command that I built from the docs examples:
```
php artisan crudmaker:new waters --migration --schema=id:increments,name:string --relationships=hasOne|App\Comment|comment,hasOne|App\Rating|rating
```
I get the following output
```
rating: command not found
AppComment: command not found
AppRating: command not found
comment,hasOne: command not found
```

**Comment by damian-nz** [comment]
For anyone else doing this while their brain is asleep it should have been this:
```
php artisan crudmaker:new waters --migration --schema=id:increments,name:string --relationships="hasOne|App\Comment|comment,hasOne|App\Rating|rating"
```

**Comment by mlantz** [comment]
Yeah unfortunately it has to be wrapped in quotes since the slashes will mess with the CLI interface
