### ISSUE TITLE
Add schema option for defining a value for a column type

### ISSUE THREAD

**Issue by Braunson** [YABhq/CrudMaker#28]
For example, in the schema option I want to define the `decimal` params.. I can't do decimal(10,4) as it throws an error that it's not in the array of valid column types. 

This applies also to the length of a string, integer, etc

**Comment by mlantz** [comment]
Currently it doesnt support the parameters of the schema just the types

**Comment by Braunson** [comment]
@mlantz This is more of a feature request 👍 Is it something planned at all?

**Comment by mlantz** [comment]
I generally build this as its needed, it sounds like a cool idea, so I'll add it to my to list :) I'm looking to put together plans for opensource projects moving forward in the next week or so

**Comment by mlantz** [comment]
So I cracked this, I've got it now to accept the parameters which is great, will release this weekend or early in the week
