### ISSUE TITLE
More descriptive error messages

### ISSUE THREAD

**Issue by Braunson** [YABhq/CrudMaker#29]
I'm receiving `Unable to generate your CRUD: Could not create the migration` but it doesn't give any information as to why, just an exception thrown with that message.

The exception is thrown [here](https://github.com/YABhq/CrudMaker/blob/2682d01035865969e819f1b31d7d714da0e916b5/src/Generators/DatabaseGenerator.php#L53) but the actual exception is never passed through.

After some debugging, the actual exception message is 'failed to open stream: No such file or directory' because the migration it's looking for wasn't created for whatever unknown reason.

**Note:** I've figured a solution for my issue but passing that error message from the initial exception to the new exception thrown would be helpful.

**If anyone's curious on what happened to get this error..** 
I tried running `artisan crudmaker:new` which failed due to incorrect `--schema` so I used Git to delete the new files, and re-ran it, however it seems Crudmaker is running something along the lines registering the new classes/controllers in the autoload file. So I simply had to run `composer dump-autoload` and re-run the artisan crudmaker command and it seemed to pass fine.

**Comment by mlantz** [comment]
Updated this so, it should collect all the messages and feed them up
