### ISSUE TITLE
Caveat: Using schema option 'comment'

### ISSUE THREAD

**Issue by Braunson** [YABhq/CrudMaker#30]
I know 'comment' isn't directly supported (as per the docs) but using it seems to work with the exception if there are any delimiters used in schema, such as:

- `:`
- `|`
- `,`

**For example:**
This will not work:
```
order:integer|default(0)|comment('This is used for when a product has multiple images, the order they are displayed in')
````

This will work __(note the missing comma in the comment statement)__:
```
order:integer|default(0)|comment('This is used for when a product has multiple images order they are displayed in')
```

Then it throws an error, not sure if this is something planned yet or not. The same goes for  usage of something like `product_id:integer|unsigned|references('id')|on('products')|onDelete('restrict')`

**Comment by mlantz** [comment]
Can you show me exactly what you had as a command, I just wrote a new test for this and it seems to work fine even with this elaborate example :)

**Comment by Braunson** [comment]
@mlantz Sure, this was the full command, it seems removing the comma as well as debugging the error thrown pointed it was trying to parse the comma in the comments string as a parameter.

```
artisan crudmaker:new ProductImages --api --migration --relationships="belongsTo|App\Product|product" --schema="id:increments,product_id:integer|unsigned|foreign('product_id')|references('id')|on('products')|onDelete('restrict'),file_name:text,order:integer|default(0)|comment('This is used for when a product has multiple images, order they are displayed in')"
```

**Comment by mlantz** [comment]
Hey @Braunson did you ever test this again with the updates?

**Comment by Braunson** [comment]
@mlantz No did not get to test this with the update, will later today

**Comment by mlantz** [comment]
Thanks @Braunson keep me posted :)
