### ISSUE TITLE
Can't publish a new module

### ISSUE THREAD

**Issue by Shocky92** [YABhq/CrudMaker#35]
Hi
I created a new module by command `module:crud` and when I try to publish it gives me an error:

>   [ErrorException]
  copy(D:\OpenServer\domains\quarxtest\D:\OpenServer\domains\quarxtest\quarx/modules/Newmoduletests/Publishes\app\Http\Controllers\Quarx\NewmoduletestsController.php): failed to open stream: No such file or directory

Seems like `base_path()` doubles, but how can I fix this?

**Comment by mlantz** [comment]
Did you ever resolve this issue? If not could you provide me with the full command you ran

**Comment by Shocky92** [comment]
Here screenshot
[http://image.prntscr.com/image/02a6e89873b049d8a184d318c95f65d3.png](url)

**Comment by mlantz** [comment]
Ok I see the issue, looks like I didn't accommodate for Windows - sorry - fix is coming today

**Comment by Shocky92** [comment]
Yes, it's working now! Thank you!
