### ISSUE TITLE
Command "laracogs:crud" is not defined

### ISSUE THREAD

**Issue by mistre83** [YABhq/CrudMaker#9]
Hi,

i've follow the installation guide for Laracogs in a new project. I've setup the Starting Kit and all works fine. I'm able to login with the default user and the dashboard works pretty well.

Now, if i try to use this command:

`php artisan laracogs:crud movie --migration --bootstrap --schema="id:increments,name:string,year:integer,length:integer,genre:string"`

I get this message:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "laracogs:crud" is not defined.                         
  Did you mean one of these?                                      
      laracogs:api                                                
      laracogs:docs                                               
      laracogs:starter                                            
      laracogs:semantic                                           
      laracogs:socialite                                          
      laracogs:billing                                            
      laracogs:notifications                                      
      laracogs:bootstrap                              
```

**Comment by casperboone** [comment]
Hi, due to a recent change you should now use crudmaker:new instead of laracogs:crud. See also this announcement: https://github.com/YABhq/Laracogs/releases/tag/v1.9.37 and the readme on this page: https://github.com/YABhq/CrudMaker.

**Comment by mistre83** [comment]
Hi @casperboone , so after setup the "Starter Kit", i have to add the CrudMakerProvider too ?

With this separation, i can just add `CrudMakerProvider `without `LaracogsProvider`, or in any cases i have first to run all steps for Starter Kit ?

**Comment by casperboone** [comment]
You do not have to do both. Just stick with the LaracogsProvider if you want all other features as well. However, if you only need the crud generator, you only have to install the crudmaker package. You can find the I nstallation details in the readme.

**Comment by mistre83** [comment]
Ok! Many thanks!
